services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
  styl-monolith:
    build:
      context: .
      dockerfile: Dockerfile
      target: local-app
    container_name: local
    restart: always
    ports:
      - "80:1323"
      - "50052:50051"
    environment:
      DB_HOST: "192.168.2.44"
